# Generated by Django 5.0.2 on 2024-04-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroyale',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
