# Generated by Django 5.0.2 on 2024-04-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroyale',
            name='player_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
